cannapagesWeb:
  component: '@sls-next/serverless-component'
  inputs:
    cloudfront:
      distributionId: ${env.DISTRIBUTION}
    bucketName: cannapages-web
    bucketRegion: us-west-1
    removeOldLambdaVersions: true
