export const StrainFilters = {
  types: ["Indica", "Sativa", "Hybrid"],
  feelings: [
    "Aroused",
    "Creative",
    "Energetic",
    "Euphoric",
    "Focused",
    "Giggly",
    "Happy",
    "Hungry",
    "Relaxed",
    "Sleepy",
    "Talkative",
    "Tingly",
    "Uplifted",
  ],
  flavors: ["Sweet", "Savory", "Earthy"],
  armoas: ["Smokey", "Nutty", "Funky"],
  helps: ["Anxiety", "Apetite", "Sleep"],
};

export const Filters = {
  strains: ["Indica", "Sativa", "Hybrid"],
  reviews: ["Most Reviewed", "Top Rated", "Lowest Rated"],
  pricing: ["Most Expensive", "Least Expensive", "On Sale"],
  type: ["Cartridge", "Flower", "Clothing", "Edible"],
  sort: ["Relevance", "Price: Low to High", "Price: High to Low"],
  price: ["$", "$$", "$$$"],
  concentrates: [
    "Budder",
    "Crumble",
    "Crystalline",
    "Ingestibles",
    "Solvent",
    "Solventless",
    "Terpenes",
  ],
  edibles: ["Candy", "Beverages", "Syrups, Sugars & Sweeteners"],
  topicals: [
    "Fragrances",
    "Hair Care",
    "Skin Care",
    "Bath & Bathing Accessories",
    "Transdermal Patches",
  ],
};
