name: CI

on:
  pull_request:

jobs:
  release:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          yarn install --frozen-lockfile
          yarn build
